import tkinter as tk
def c():
    a = float(e1.get())
    b = float(e2.get())
    r.config(text=f"Answer:{a+b}")
w = tk.Tk()
w.title("Sum Calculator")
f = tk.Frame(w)
f.pack(anchor="w",padx=10,pady=10)
ef=tk.Frame(f)
ef.pack(side="left")
e1=tk.Entry(ef,width=20)
e1.pack(pady=2)
e2=tk.Entry(ef, width=20)
e2.pack(pady=2)
b=tk.Button(f, text="Calculate",width=20,height=3,command=c)
b.pack(side="left",padx=10)
r=tk.Label(w,text="Answer:")
r.pack(anchor="w",padx=10,pady=10)
w.mainloop()
